### ISSUE TITLE
SEED flag in EOPTION or COPTION silently accepts invalid values

### ISSUE THREAD

**Issue by fsoubelet** [MethodicalAcceleratorDesign/MAD-X#1004]
Hi,

When setting the `seed` flag in either the `eoption` or `coption` commands, the manual specifies that "A SEED value is an integer inthe range [0...999999999] (default: 12345678)."

However, when providing a value outside of this range MAD-X silently accepts it. I'm not sure what the software decides to do internally, but it probably should at least give the user a warning, or eventually crash if the seed should really not be in this range.

To reproduce, one can simply enter `eoption, seed=1234567898765432123;` in the MAD-X interpreter for instance, or giving any other value superior to `999999999`.

**Comment by ghislain-roy** [comment]
The relevant part of the code in mad_rand.c is `= abs(seed)%MAX_RAND`  where `MAX_RAND=1000000000`

The documentation is therefore correct although there is no explicit check and warning to the user in the cases you mentioned. 
I will however update the documentation for `EOPTION` to indicate that `SEED=integer` instead of the mistaken `SEED=real`
