### ISSUE TITLE
EALIGN DPSI errors on MB gives wrong tunes in PTC_ALIGN

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#199]
*Issue migrated from trac ticket # 199*

**component:** ptc_module | **priority:** major
___
#### 2013-03-28 11:39:34: ewen.hamish.maclean commented

date: 2013.03.28

I have seen that on applying the WISE misalignments in a thin lattice there is a discrepancy in the tune between mad and PTC of ~3x10^-3^. I have now tried applying systematic misalignments to several classes:

The MQ, MS and MO showed no discrepancy. However applying rotational misalignments (DPSI) to the MB did. 

On applying the following misalignments:

 SELECT,FLAG=ERROR, CLEAR;
SELECT,FLAG=ERROR,PATTERN="!^MB\.";
EOPTION,ADD=TRUE;
EALIGN,DX:=0,DY:=0,DPSI=0.0005;

I see differing results for the the tune and the closed orbit:

MADX
@ Q1               %le         64.30683527
@ Q2               %le         59.32312608
@ DQ1              %le         2.143945892
@ DQ2              %le         1.872293787
@ XCORMS           %le     7.710855603e-05
@ YCORMS           %le      0.001560382856

PTC
@ Q1               %le        0.3099990862
@ Q2               %le         0.319999275
@ DQ1              %le         1.999981567
@ DQ2              %le         1.999983536
@ XCORMS           %le                   0
@ YCORMS           %le                   0

Is it that this may be due to a bug in PTC_ALIGN?

___
#### 2013-03-28 11:40:31: @ldeniau uploaded file [`job.4bug2.madx`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/199/job.4bug2.madx) (2.2 KiB)

___
#### 2013-03-28 11:41:05: @ldeniau edited the issue description

___
#### 2013-03-28 11:42:11: @ldeniau edited the issue description

___
#### 2013-03-28 11:44:02: @ldeniau edited the issue description

___
#### 2013-10-03 09:34:12: @ldeniau changed status from *new* to *assigned*

**Comment by piotrskowronski** [comment]
The problem was the thin lens lattice. Actually, the rotational misalignments were not taken into account at all.

Thin lattice should not be used in PTC because it is not supported at all by the PTC author. The 
implementation is copy paste of thin multipole from MAD and it is far from being well integrated within PTC and it is one of the example cases.

I managed to find a hack and now your example gives approximate agreement with MADX orbit and tune.
Still, thick lattice should always be used, because it produces orders of magnitude more accurate result. 

Submitted in pull request #549
