### ISSUE TITLE
AC dipole in MADX

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#397]
*Issue migrated from trac ticket # 397*

**component:** ptc_track | **priority:** major | **keywords:** Ac dipole, rf multipole, ptc, tracking
___
#### 2016-10-17 17:19:26: Piotr.Skowronski@cern.ch commented

I'm back to you because I still cannot make PTC give trustworthy results
with the RFMULTIPOLE used as an AC dipole.

The modification suggested by Piotr (set a non-zero voltage) looked to
me to act as accelerating cavity: indeed turn-by-turn the T coordinates
increases linearly and only because of this the horizontal ones change
at the fifth or lower digit (in PTC). I'm not looking at this feature,
as I need an RF (AC) dipole only.

I modified the MADX file, with included a gnuplot script for a quick
comparison between PTC (thick) and MADX (thin) tracking results. I see
that MADX tracking is very responsive to any change of the excitation
frequency, i.e. when approaching the tune, as it should be, whereas
results from PTC_TRACK give very different results and are still
independent from the excitation frequency.

In the zip file I also included two plots comparing MADX and PTC
tracking with two different excitation frequencies, one at -0.10 from
the tune, the second at -0.01, as defined in the line:

ACH_FREQ:=1/(50/clight*1e6)*(0.3325-0.01); ! [MHz]

Two things I don't understand:

1. why PTC and MADX x coordinates are so different in units and pattern?

2. Why PTC x coordinates don't change when varying the excitation freq.?

I would appreciate if you could have a look at the attached example and
give me your feedback.

Thanks a lot in advance!

P.S. I would desperately like to avoid the thin MADX tracking for our
lattice since it is very difficult to rematch it recovering all original
linear and nonlinear parameters.

Ciao
Andrea 

https://www.dropbox.com/s/24prjxj3d1pd8n0/CERN_test_ACdipole.zip?dl=0

**Comment by ldeniau** [comment]
Status of this issue?

**Comment by piotrskowronski** [comment]
[CERN_test_ACdipole.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1643920/CERN_test_ACdipole.madx.txt)
Hi Andrea,
There are a few issues here. You need to have an rf cavity with voltage, otherwise the code forces NOCAVITY=true, and your RF multipoles are not active. It does not have to be the AC dipole, just define a separate cavity of your machine, or if it is not important define one with a very small voltage.

The main problem is totalpath=false. In this case the code does not know the time of flight and the electrons see constant  phase of  RF cavity. When I put totalpath=true I got a good agreement of amplitude pattern vs the exciter tune, when I compared AC dipole (that I just implemented) with the RF multipole. I attach the modified script.

AC dipole with ramp-up and ramp-down capabilities will be available in the next release.

Cheers,
Piotr
