### ISSUE TITLE
Time variable definition in manual

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#470]
In section 1.7 variable  there are the following definitions in order:

twiss: T = −ct, [m]
summ: ORBIT5 The T (= ct, [m]) component of the closed orbit.
track: T = −c∆t, [m]

The correct one should be T=−c∆t also in Twiss.

ORBIT5 is equal -T, it is somehow correct in the parenthesis but it is a bit confusing. I would rewrite 

ORBIT5 Minus the T (ORBIT5 = -T = c ∆T ) ...

It still puzzling to me why ORBIT5 has the negative sign, but this is another problem.

Do you confirm that also internally twiss and track use (T=  −c∆t) as fifth element of the orbit, while, only internally, PTC is using (-T = c Delta t) and the sign is always flipped back and forth in the I/O interfaces?

**Comment by tpersson** [comment]
We confirm that it is c ∆T that is used. The documentation is uptaded with the following pull request:
#487 

Thanks for spotting and reporting it!

**Comment by rdemaria** [comment]
Do you also confirm the last point? It can be related to #480.

**Comment by piotrskowronski** [comment]
I did not answer this because I am puzzled by this question.
What is the difference between T= −c∆t and -T = c Delta t ?

In PTC, after travelling a drift, a slower particle (with negative deltap) has positive T.

So, the time variable in PTC is opposite to the MADX one and in theory should be always swapped in the translation between PTC and MADX. It is not always the case because handling TOTALPATH flag makes it difficult.

**Comment by piotrskowronski** [comment]
I am not able to close the issue because not understanding the question I don't know if I confirmed it or not.
Riccardo, please let us know.

**Comment by rdemaria** [comment]
Do input and output of PTC follow the madx convention or PTC convention? Is
the LAG of the cavities transferred consistently? By the way, does PTC (in
madx) support crab cavities or RF multipoles?

**Comment by piotrskowronski** [comment]
[rfmultlag.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1651720/rfmultlag.madx.txt)
Yes, the input and output is converted, end if it is not it would be a bug.
The LAG is transformed, however there was a bug (sign flip) that I corrected now.
Yes, RF multipoles are supported. I attach an example script illustrating the response of an RF Dipole to LAG flip. 
Concerning the RF elements I also added to the documentation remarks concerning the PTC switches.
In short:
- There must be at least one RF cavity with voltage otherwise all RF elements, including RFMULTIPOLE, are disabled
- TIME=true must be used unless the beam is fully relativistic
- If TOTALPATH=false then LAG is always respected, but time of flight effects are than neglected (including ring length effect). So cavity detuning effect will not be visible.
- If TOTALPATH=true, the  cavity detuning and time of flights are visible, but than LAG of each cavity must be adapted by the user to account for cavity S position.
