### ISSUE TITLE
question: MAXAPER T limit for TRACK

### ISSUE THREAD

**Issue by listoel** [MethodicalAcceleratorDesign/MAD-X#475]
It looks like there is a hard limit on the T value of MAXAPER for TRACK, somewhere between 119 and 120. Is there a way around this limitation? (I run into the limit when tracking a low energy coasting beam for many turns.)

**Comment by tpersson** [comment]
Hi, 
I started looking into it now but it is not so obvious to me at this point. Would you have an example of when this occurs (as simple as possible) and I could investigate more in detail. 

best regards
Tobias

**Comment by listoel** [comment]
Hi Tobias,

Sorry for not making a minimal example earlier, I see now that the issue is slightly different from what I described. I can produce 2 errors that I would not expect from what is in the manual.

The first (in example1.txt) is that initializing T greater than some limit invokes a fatal error. From what I saw this limit is linked to the length of the sequence, and equal to a bit more than 1.5 times the sequence length. This is not an issue for me at the moment, but I've included it to be complete.

The second issue (in example2.txt) is the one i would like help with, and is actually due to the introduction of an RFCAVITY element. I want to simulate a so-called betatron core, which is an element that gives the beam a fixed kick in longitudinal momentum each turn. I do this by using 
RFCAVITY, LAG=0.25, HARMON=0;
which according to the manual will result in an element with an effect delta(E) = VOLT*sin(pi/2) = VOLT. It seems that this element still has a size assigned to its RF bucket, even though there is no bucket. Even when the voltage is set to 0 particles are lost on the 'RF bucket aperture'. To me it would make more sense if the T aperture of an RFCAVITY is set to the one specified by MAXAPER if either
- HARMONIC=0
- VOLT=0
And for the code I'm working on, I'm interested in the HARMONIC=0 case.

Best regards,
Linda

[example1.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1372085/example1.txt)
[example2.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1372086/example2.txt)

**Comment by tpersson** [comment]
Hi Linda, 
For the first example, I think indeed I know where in the code it is and I think it is. I will have a look and I think you can set something to change that. 

The second question: I see your point.  I will try to look into it as soon as possible and get back to you.

best regrards
Tobias

**Comment by tpersson** [comment]
Hi Linda, 
For tracking there is an option called track_harmon. I can't find it anywhere in the documentation but  if you don't set it then it is equal to 1. The calculation is then circumference/1*beta. (relativistic beta). So in some sense it is saying that when the particle is one turn after it is outside the bucket. This clearly needs to be documented and I am not even sure that this should be a default behaviour. Anyhow, for your problem the easiest is just to set it track_harmon = 0 
 RUN, TURNS=5000,track_harmon=0, MAXAPER={0.08,0.05,0.08,0.05,500.0,0.1}, FFILE=1;
Then this t_max because INF and you will not run into the problem. Your normal MAXAPER constraints should not be affected. 

Let me know if this solves your problem and I will update you with how we decide to proceed with this. 

best regards
Tobias

**Comment by listoel** [comment]
Hi Tobias,

Thank you for this solution, it works like a charm!

Cheers,
Linda

**Comment by tpersson** [comment]
This is now documented in #510.
