### ISSUE TITLE
Closed orbit search using stochastic switch in ptc

### ISSUE THREAD

**Issue by ttydecks** [MethodicalAcceleratorDesign/MAD-X#566]
Hi,
using the stochastic switch in ptc closed orbit is found by ptc_twiss but not by ptc_track if both are called:

PTC_SETSWITCH, debuglevel=1, maxacceleration=false, exact_mis=false, time=true, totalpath=false, fringe=true, radiation=true, stochastic=true, envelope=true;

PTC_TWISS, ICASE=6, CLOSED_ORBIT, NO=2, RMATRIX;

PTC_TRACK, ICASE=6, CLOSED_ORBIT, RADIATION;

Best regards,
Tobias

**Comment by piotrskowronski** [comment]
With stochastic kicks the closed orbit search has chance to find a solution, because it is a moving target. Implemented switching off stochastic during for the search. 
Implemented also a status check after from the closed orbit search in ptc_track, so now an error is emitted when it fails.

Implemented in PR #565
