### ISSUE TITLE
MADX fails on windows 10 April 2018 update

### ISSUE THREAD

**Issue by bogomyag** [MethodicalAcceleratorDesign/MAD-X#616]
After windows 10 update madx fails to start. The new 5.04.00 and the old one 5.03.07.

Here is a message

A s s e r t i o n   f a i l e d !

 P r o g r a m :   C : \ U s e r s \ a v b o g \ D o c u m e n t s \ W o r k \ M A D X \ m a d x - w i n 6 4 - g n u . e x e
 F i l e :   s r c / m a d _ m a c . h ,   L i n e   2 2

 E x p r e s s i o n :   d s t   & &   s r c   & &   s i z   <   I N T _ M A X

**Comment by ldeniau** [comment]
This assertion is a guard against bad use of the function. We need a working and update Windows 10 to investigate, so this may take some time...

**Comment by hyjz2018** [comment]
Compatibility mode of win8 on win10 doesnt work ,this drives me crazy...

**Comment by ldeniau** [comment]
Hi Anton,

It seems that the problem is on “normal” Windows 10 after the so called “April update", and we don’t have (yet) access to such Windows 10. Our Windows 10 is patched by the CERN CMF system and everything is working fine on it. So we will investigate on a laptop that has a non-CERN Windows 10 + April update installation to investigate the problem and try to fix it. I let you know as soon as we have news.

Best,
Laurent.

**Comment by ldeniau** [comment]
The problem was solved by PR #645. This will be fix in the coming release next week.
