### ISSUE TITLE
Feature Request:  esave command only dumps selected columns

### ISSUE THREAD

**Issue by z-duan** [MethodicalAcceleratorDesign/MAD-X#684]
As far as I understand, the "esave" command currently dumps all the errors (all columns in the "efield_table_cols") to a file. To facilitate a more convenient analysis of certain types of errors (say a few columns rather than all columns) introduced in previous commands, I think it makes sense to modify the "error_esave" function in "mad_elemerr.c", to enable selection of the desired columns of errors via the "select, ...., column=..." command, which is the default feature in twiss and other commands. 

Zhe Duan @ IHEP

**Comment by tpersson** [comment]
A table containing the information about just a few errors can now be saved. In order to do it a new ETABLE command has been added. This is to avoid confusion and break backwards compatibility. 

After you have assigned the errors you can simple do the following:
select,flag=mye, column=name, k0l, k1s, DX;
ETABLE, TABLE=mye;
write, table=mye, file="mye.err";

This implemented in #725 and will be available in the next release.
