### ISSUE TITLE
STEP ignored in VARY for LMDIF and JACOBIAN 

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#702]
The stepsize to compute the response matrix used in LMDIF and JACOBIAN is ignored and this sometimes causes issues in matching problems.

The response matrix is calculated using finite differences in the routine `fdjac2`. The step size is 1e-4 times the absolute value of each variable or 1e-16 when the value is zero. This causes issues when a variable value is very small, for instance due to numerical errors, because the stepsize becomes too small to be usable in finite differences.

The proposal is to use STEP defined in VARY to impose a stepsize that is reasonable for the problem or use the present strategy when STEP is not defined.

**Comment by ldeniau** [comment]
For the backward compatibility, it was agreed with Ricardo to add a new attribute named "fdstep" to avoid confusion. This attribute is for *now* attached to option and unique for all variables, see PR #921. The reason is that Jacobian method reduce the number of variables, shifting the VARY statement arbitrarily...
