### ISSUE TITLE
Usage of wrong SIGE and SIGT parameters in IBS and Touschek modules

### ISSUE THREAD

**Issue by JohnMSmith** [MethodicalAcceleratorDesign/MAD-X#756]
For some reason, IBS module and Touschek module show values of SIGE and SIGT that differ from ones entered in BEAM before. That makes IBS and Touschek lifetime calculations give wrong results.

For script applied you can see, that 
**beam->sige         =    0.0008708186096 ;
beam->sigt         =     0.005526387947;**
but mentioned modules use 
 **sigt        5.2494380845914262E-003
 sige        9.1675250442853069E-004**.
[Script.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/3037750/Script.zip)

**Comment by JohnMSmith** [comment]
I suspect this recalculation happens in the following function
https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/c13a93bfc37e386a15f7e82a68813b182f7689e2/src/mad_beam.c#L391

**Comment by tpersson** [comment]
I will have a look and try to understand why the numbers are different.

**Comment by tpersson** [comment]
In the script you have specified the et, sige, sigt which is over specifying since given the et you can calculate the sige and sigt which is what is done in the file you pointed out.  I think this is the right behavior but should be documented. If however noticed that the behavior was wrong if you didn't specify a et. This will be changed in the next release and the documentation will be updated.

**Comment by JohnMSmith** [comment]
EMIT calculates SIGE and SIGT. I see these values as correct and expect them to be used in the following calculations. But those values aren't used in IBS and Touschek. Instead, they are being recalculated before actual growth time calculation (in IBS) and normally it shoudn't change SIGE and SIGT (I guess).

**Comment by JohnMSmith** [comment]
So, I've removed lines 435-449 and made a build for myself and now SIGT and SIGT values in IBS and Touschek modules are the same as the values calculated by EMIT in BEAM.

**Comment by tpersson** [comment]
In the new version the logic will be the following. There still has to be a precedence since defining ET, SIGT and SIGE can mean that the values are non-consistent.  In your example all were defined so it was always calculated from ET. However, in your case even if you would have removed the ET  the problem would have been that ET was always used because the check was for zero even thought the default was 0.001. Meaning that it was always converted from ET to SIGE and SIGT. 

The following will be added to the manual:
The order of precedence for the longitudinal emittance is in the following order \texttt{ET->(SIGT and SIGE)}, \texttt{(SIGT and SIGE)->ET}, \texttt{(SIGT)->(ET and SIGE}, \texttt{(SIGE)->(ET and SIGT}. This means that if you define a \texttt{ET} this values will be used to override any value that you might have set for \texttt{SIGT and SIGE}.

**Comment by JohnMSmith** [comment]
I don't see what your correction have changed. Maybe we just didn't understand each other.
Let's clarify some steps.

EMIT updates BEAM parameters to equilibrium values. SIGT and SIGE calculated using ET in such a way that ET = SIGT*SIGE. 
After that I'm setting in BEAM new coupled transverce emittances. ET, SIGE and SIGT don't have to be set in the new BEAM because the values in the BEAM are the same anyway. (beam->sige = 0.0008708186096 ; beam->sigt = 0.005526387947;) But it's needed to be done if I'm about to calculate IBS iteratively. 
After I call IBS I can see global parameters for the machine. Ex and Ey are as I defined them, Et is as EMIT calculated. SIGT and SIGE among those parameters are different from equilibrium ones (sigt 5.2494380845914262E-003; sige 9.1675250442853069E-004), but SIGE*SIGT = ET as it should. 

Your correction haven't changed that. The way I see it SIGT and SIGE are calculated wrong either in EMIT or somewhere in this function. I understand the thing about the order of precedence but I don't see how it explains the change in values. Yes they could be recalculated, but why are they different?

**Comment by tpersson** [comment]
EMIT's way of calculating SIGT and SIGE is more correct. In that way of doing it also the horizontal and vertical will have an impact on the SIGT and SIGE while in the mad_beam.c it is only considered to be independent of the horizontal and vertical. To change this would need to require that the ex and ey is also defined before calculating SIGT and SIGE. 
However, I have added so that in case you specify all ET, SIGE and SIGT you will always keep the values in the calculations. This can of course lead to inconsistencies but this is then left up to the user to handle.

Does that sounds reasonable? 

I also would like to thank you for reporting these issue!
