### ISSUE TITLE
Misalignment of thin dipole (multipole) 

### ISSUE THREAD

**Issue by tpersson** [MethodicalAcceleratorDesign/MAD-X#872]
The problem was reported by @rdemaria  and I had a look and it derives from the suelem routine that changes the reference frame at the exit of the element. The orbit seems correct and is also the same as obtained by PTC but the phase advance becomes wrong when a large misalignment is applied. I will not investigate this now but this should be checked. 

 
noerr: sequence, l=2;
m1:multipole, knl={0.0002}, at=1;
!kickm:kicker, vkick=0.1, at=1;
endsequence;
beam;
use,sequence=noerr;
select, flag=error, pattern=m*;
ealign, dpsi=pi/2;
SELECT, FLAG=TWISS, column= name,s, betx,bety, x, y, MUX, MUY;
twiss, betx=1, bety=1, file="twiss.out";

ptc_create_universe;
  ptc_create_layout, model=1, method=6, nst=5, exact=true, closed_layout=true;
  ptc_align;

  !!!!!       T I M E   F A L S E,   T O T P A T H  F A L S E
  ptc_setswitch, exact_mis=true, time=false, totalpath=false;
  
  
  ptc_twiss, table=twiss, icase=5, no=4, betx=1, bety=1;
  write, table=twiss, file="ptc_twiss";
  write, table=ptc_twiss_summary, file="ptc_summary";
  
ptc_end;

**Comment by aoeftiger** [comment]
Indeed, I could reproduce this with both exact_mis=true and false in PTC: https://github.com/aoeftiger/sixtracklib_pyht_playground/blob/2a3f81b7a74e4d18501101269564bc1c88b2ff94/sis100/2020-01-10--multipole-error-comparison-MADX-STL/ThinDipole_with_dpsi-entering_on_axis-PTC.ipynb

This issue accumulates to a 20% error in transverse coordinates after 20'000 turns e.g. for the FAIR synchrotron SIS100:
![image](https://user-images.githubusercontent.com/6876174/79364535-c1dc4580-7f49-11ea-8a5c-926e3bbe2cd7.png)

(where otherwise I observe 1e-6 difference without dpsi errors or even 1e-12 difference when additionally switching off RF... the reference here is SixTrackLib and/or PySixTrack.)

**Comment by tpersson** [comment]
The beta functions comes out identical but the phase advance is wrong. This should defintley be understod but the manual is writing that it should be used for small angles and in this case it seems to behave correctly.

**Comment by aoeftiger** [comment]
Yes, let's say for small angles the error is small enough not to be obvious :smile:

**Comment by rdemaria** [comment]
Closing now as it looks to be related to the approximations used in the misalignments.
