### ISSUE TITLE
Calculation of crabcavity R and T matrix not correct in MADX and PTC

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#981]
R and T matrix are not computed correctly in mad-x when the crabcavity have zero lengths and regardless of length is PTC. The attached script shows that R15 for HL-LHC in IP1 is zero when in MAD-X crabcavity have a zero length and in PTC.
[job_round.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5932906/job_round.txt)

In MADX this is due to a combination of side effects:
- https://github.com/MethodicalAcceleratorDesign/MAD-X/blame/master/src/twiss.f90#L8693
- https://github.com/MethodicalAcceleratorDesign/MAD-X/blame/master/src/twiss.f90#L6824
- https://github.com/MethodicalAcceleratorDesign/MAD-X/blame/master/src/twiss.f90#L834

In PTC the problem has not been identified

**Comment by giadarol** [comment]
If I understand correctly, there is some duplication between RFMultipole and CrabCavity elements. We might want to port all the functionality in RFMultipole and call it from CrabCavity for backward compatibility.

**Comment by tpersson** [comment]
I think this issue is solved with the PR and the R15 is also consistent with PTC except for the fact that PTC uses minus time so there is a sign change. However, there is still might be something strange when there is a length of the crabcavity in PTC. I am not sure if it is just due to the modelling but it should at least be checked. I would suggest closing this issue and open one specially on that. What do you think?

**Comment by rdemaria** [comment]
The sign is due to PTC using -t or something else?

**Comment by tpersson** [comment]
Yeah the sign was indeed to this. For me it is all consistent.
